### ISSUE TITLE
Mouse pan/zoom

### ISSUE THREAD

**Issue by danielmeloalencar** [easylogic/editor#95]
Please consider the pan / zoom feature using the mouse. As it is, it is currently not very good.
Consider this: 
https://www.jqueryscript.net/zoom/jQuery-Plugin-For-Panning-Zooming-Any-Elements-panzoom.html

**Comment by danielmeloalencar** [comment]
As it is, we lose a lot of productivity

**Comment by easylogic** [comment]
@danielmeloalencar  

I implemented panzoom. 

Please test it on https://editor.easylogic.studio.  

Thanks.

**Comment by danielmeloalencar** [comment]
Very well. 
How to use the pan? I can only zoom, using CTRL + SCROLL

**Comment by easylogic** [comment]
@danielmeloalencar 

I implemented it on wheel event.  

ctrl + wheel or trackpad zoom event are zooming.

Only wheel event is panning. 

Because I have only mac book pro,  I couldn't implement on all devices. 

If you have any good ideas on how to panzoom, please share. 

Let's consider how to implement it.

**Comment by easylogic** [comment]
@danielmeloalencar  

I added a feature  to panning by space key + drag. 

Please test it on https://editor.easylogic.studio .

Thanks.

**Comment by danielmeloalencar** [comment]
WOW! Now is perfect! Thank you!
